### ISSUE TITLE
ImportError: No module named 'encoding.version'

### ISSUE THREAD

**Issue by Nqabz** [ytian8/DSN_RS#1]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    import encoding.utils as utils
  File "/data/2019-projects/DSN_RS/encoding/__init__.py", line 12, in <module>
    from .version import __version__
ImportError: No module named 'encoding.version'

**Comment by ytian8** [comment]
It seems like the PyTorch-Encoding toolkit is not installed correctly. Could you please try to install from the source?

git clone https://github.com/zhanghang1989/PyTorch-Encoding && cd PyTorch-Encoding
python setup.py install
